#!/usr/bin/env bash
# This script installs and configures Nginx web server

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the /var/www/html directory and index.html file
sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx service
sudo service nginx restart
