#!/usr/bin/env bash

# Install a Nginx web server listening on port 80.
# When querying Nginx at its root / with a GET request, it returns a page that contains the string 'Hello World!'.
# Configures a directive of the Nginx server to redirect to another page with 301 HTTP Code.
# Configures a custom 404 page that contains the string 'Ceci n'est pas une page'.

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
custom_conf="/etc/nginx/conf.d/custom.conf"

apt update
apt install -y nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create a new configuration file for custom settings
cat > "$custom_conf" << EOF
server {
    listen 80 default_server;
    root /var/www/html;

    # Redirect to YouTube video
    rewrite ^/redirect_me/$ $link permanent;

    # Custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Include the custom configuration file in the main Nginx configuration
echo "include $custom_conf;" >> /etc/nginx/nginx.conf

service nginx restart
