#!/usr/bin/env bash
# Configure the server with the X-Served-By custom HTTP header

# Update package lists
sudo apt-get update

# Install Nginx if it's not already installed
sudo apt-get install -y nginx

# Get the hostname
HOSTNAME=$(hostname)

# Remove default Nginx configuration
sudo rm -f /etc/nginx/sites-enabled/default

# Create a custom Nginx configuration file
sudo tee /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name ${HOSTNAME};

    location / {
        try_files \$uri \$uri/ =404;
    }

    add_header X-Served-By "${HOSTNAME}";
}
EOF

# Create a symlink for the custom configuration
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
sudo systemctl restart nginx
