#!/usr/bin/env bash
# Install and configure HAProxy load balancer

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Create HAProxy configuration file
sudo bash -c 'printf "%s\n" "
global
    log /dev/log local0
    maxconn 2000
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server web-01 531206-web-01:80 check
    server web-02 531206-web-02:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null'

# Enable HAProxy service and start it
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy
sudo systemctl restart haproxy
